# Generated by Django 4.2.4 on 2023-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
