# Generated by Django 4.2.4 on 2023-10-10 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='recipient_name',
        ),
    ]
